site_name: Larq
site_description: "An Open Source Machine Learning Framework for Training Extreme Quantized Neural Networks"
site_author: "Plumerai"
site_url: "https://larq.dev/"

nav:
  - Learn:
      - Introduction: index.md
      - User Guides:
          - Key Concepts: guide-key-concepts.md
          - Building BNNs: guide-bnn-architecture.md
          - Training BNNs: guide-bnn-optimization.md
      - Examples:
          - Introduction to BNNs with Larq: examples/mnist.ipynb
          - BinaryNet on CIFAR10: examples/binarynet_cifar10.ipynb
          - BinaryNet on CIFAR10 (Advanced): examples/binarynet_advanced_cifar10.ipynb
  - API:
      - Layers: api/layers.md
      - Quantizers: api/quantizers.md
      - Activations: api/activations.md
      - Constraints: api/constraints.md
      - Callbacks: api/callbacks.md
      - Optimizers: api/optimizers.md
      - Math: api/math.md
      - Models: api/models.md
  - Models:
      - Larq Zoo: models/index.md
      - Examples: models/examples.md
      - API: models/api.md
  - Community:
      - Papers using Larq: papers.md
      - Contributing Guide: contributing.md
      - Code of Conduct: code-of-conduct.md
  - Why Larq?:
      - About: about.md
      - FAQ: faq.md

repo_url: https://github.com/larq/larq
repo_name: larq/larq
edit_uri: ""
theme:
  name: material
  logo:
    icon: developer_board
  palette:
    primary: blue
    accent: blue
  feature:
    tabs: true

extra:
  social:
    - type: "github"
      link: "https://github.com/larq"
    - type: "twitter"
      link: "https://twitter.com/PlumeraiHQ"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/plumerai/"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: plot-activation
          class: larq-activation
          format: !!python/name:plot_activation.html_format
  - pymdownx.arithmatex
  - toc:
      permalink: true

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML"

extra_css:
  - custom.css

plugins:
  - search
  - minify:
      minify_html: true
  - mknotebooks:
      execute: false
