site_name: Documentation
title: Larq
site_description: "Larq is an open-source deep learning library based on TensorFlow and Keras for training neural networks with extremely low-precision weights and activations, such as Binarized Neural Networks."
site_author: "Plumerai"
site_url: "https://docs.larq.dev/"

nav:
  - Larq:
      - Getting Started: index.md
      - User Guides:
          - Key Concepts: larq/guides/key-concepts.md
          - Building BNNs: larq/guides/bnn-architecture.md
          - Training BNNs: larq/guides/bnn-optimization.md
      - Tutorials:
          - Introduction to BNNs with Larq: larq/tutorials/mnist.ipynb
          - BinaryNet on CIFAR10: larq/tutorials/binarynet_cifar10.ipynb
      - API:
          - Layers: larq/api/layers.md
          - Quantizers: larq/api/quantizers.md
          - Activations: larq/api/activations.md
          - Constraints: larq/api/constraints.md
          - Callbacks: larq/api/callbacks.md
          - Optimizers: larq/api/optimizers.md
          - Math: larq/api/math.md
          - Models: larq/api/models.md
          - Metrics: larq/api/metrics.md
  - Zoo:
      - Getting Started: zoo/index.md
      - Tutorials: zoo/tutorials.ipynb
      - API: larq/api/larq_zoo.md
  - FAQ: faq.md

repo_url: https://github.com/larq/larq
repo_name: larq/larq
edit_uri: ""
theme:
  name: material
  custom_dir: docs-theme
  logo: images/logo-big-font.svg
  favicon: images/favicon-32.png
  palette:
    primary: larq
    accent: larq

extra:
  social:
    - type: "github"
      link: "https://github.com/larq"
    - type: "twitter"
      link: "https://twitter.com/PlumeraiHQ"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/plumerai/"

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: plot-activation
          class: larq-activation
          format: !!python/name:plot_altair.plot_activation
        - name: plot-altair
          class: larq-altair
          format: !!python/name:plot_altair.html_format
        - name: netron
          class: larq-netron
          format: !!python/name:netron_link.html_format
  - pymdownx.arithmatex
  - toc:
      permalink: true

extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
  - "https://cdn.jsdelivr.net/npm/vega@5"
  - "https://cdn.jsdelivr.net/npm/vega-lite@4"
  - "https://cdn.jsdelivr.net/npm/vega-embed@6"

extra_css:
  - custom.css

google_analytics:
  - "UA-144491780-1"
  - "auto"

plugins:
  - search
  - minify:
      minify_html: true
  - mknotebooks:
      execute: false
